#!/bin/sh
until confd -onetime -node $ETCD_IP; do
    echo "[nginx] waiting for confd to create initial nginx configuration."
    sleep 5
done

echo "[nginx] confd is now monitoring etcd for changes..."
confd -watch=true -node $ETCD_IP            
